### PR TITLE
[Bug]: User session is invalid when logging in consecutively, resolves #116

### LINKED ISSUE #116: [Bug]: User session is invalid when logging in consecutively
### Bug Summary

The `setupGameAsP0()` helper occasionally throws a Type Error due to a 403/forbidden response

### Detailed Description

Cypress appears to be attempting to create a new property on a 403 'error' response when the backend is only sending the string `forbidden`

```
     TypeError: Cannot create property 'stack' on string 'Forbidden'        
                                                                            
Because this error occurred during a `before each` hook we are skipping the 
remaining tests in the current suite: `Countering One-Offs`
```
This happens unpredictably across different tests in the `beforeEach()` hook when using the `setupGameAsP0()` helper function. The issue is likely that one of the commands in that helper function is firing before the appropriate setup has completed, causing the backend to throw a `forbiden()` response

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps to Reproduce

1.
2.
3.

### PR DESCRIPTION
**Pull request by seriouslysean**
## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle#linting-formatting))
- For New Features:
  - [x] Have tests been added to cover any new features or fixes?
  - [x] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

This is an incredibly annoying issue and has to do with using websockets to refresh the user's session. We need to actually use XHR requests to make sure the headers come back with the proper cookies so they can be set by the server for the browser to action on. For example, as it stands currently this will happen:

1. initial load I get `s%3AyWGFsNo7JX0ROG1xG2lJdBd0DsKHsnPt.TGqw%2FLu5dL0Havuk6enxTnbKPBNSmfRfaUIFcgbOTl8` (initial value)
2. On login, I get `s%3AyWGFsNo7JX0ROG1xG2lJdBd0DsKHsnPt.TGqw%2FLu5dL0Havuk6enxTnbKPBNSmfRfaUIFcgbOTl8` (same value)
3. On logout, I get `s%3AyWGFsNo7JX0ROG1xG2lJdBd0DsKHsnPt.TGqw%2FLu5dL0Havuk6enxTnbKPBNSmfRfaUIFcgbOTl8` (same value, this needs to be deleted 😎)
4. On relogin, I get `s%3AyWGFsNo7JX0ROG1xG2lJdBd0DsKHsnPt.TGqw%2FLu5dL0Havuk6enxTnbKPBNSmfRfaUIFcgbOTl8`
5. On reload, I get `s%3AEVw6BGnlugAXdl5DJXYvLTa_do8D1rKj.yYgV4FnF7XNT1yvvd8cyBeg7g5RJ84%2Fm31HCbFwZMhk` (different value)

Ideally after each session refresh (sign in, sign up, login, logout), that cookie should be changing. With this PR it does but it comes with some downsides for the time being until I can work in socket reconnects or socket session refreshes.

This is also the reason for the intermittent Cypress failures we've been seeing in all of our PRs, and will directly unblock https://github.com/cuttle-cards/cuttle/pull/117.

### CODE REVIEW

File: client/js/plugins/sails.js [hunk 1]
```diff
@@ -6,6 +6,11 @@ const { isProd } = require('../../../utils/config-utils');
 
 export const io = require('sails.io.js')(require('socket.io-client'));
 
+export const reconnectSockets = () => {
+  io.socket.disconnect();
+  io.socket.reconnect();
+};
```
Comment (seriouslysean) [inline client/js/plugins/sails.js:12]: We need this to refresh any session connections in progress to make sure they get the new session id when the user logs in or out and the cookie changes.

File: client/js/store/modules/auth.js [hunk 2]
```diff
@@ -1,8 +1,36 @@
-import { io } from '../../plugins/sails.js';
+import { io, reconnectSockets } from '../../plugins/sails.js';
 import { ROUTE_NAME_LOBBY, ROUTE_NAME_GAME } from '@/router';
 
 import { getPlayerPnumByUsername } from '_/utils/game-utils.js';
 
+async function handleLogin(context, username, password, signup = false) {
```
Comment (seriouslysean) [inline client/js/store/modules/auth.js:6]: This was the biggest lift, I had to rewrite all of the sign in/sign up logic to use fetch instead of the sockets, much like we do for the status check due to the way that browsers get and set cookies from the server.

File: api/controllers/UserController.js [hunk 3]
```diff
@@ -34,33 +31,26 @@ module.exports = {
...
-            });
-        })
-        .catch(() => {
-          return res.badRequest({
-            message: 'Could not find that user with that username. Try signing up!',
-          });
-        });
-    } else {
-      return res.badRequest({ message: 'A username must be provided' });
+  login: async function (req, res) {
```
Comment (seriouslysean) [inline api/controllers/UserController.js:39]: I also took the opportunity to rewrite the sails methods while I was in here to consolidate them and get them updated to async await.

File: client/js/store/modules/auth.js [hunk 4]
```diff
@@ -1,8 +1,36 @@
...
+      credentials: 'include',
+    });
+    const data = await response.json();
+    if (response.status !== 200) {
+      throw data.message;
+    }
+    // If the response was successful, the user is logged in
+    context.commit('authSuccess', username);
+    reconnectSockets();
+    return;
```
Comment (itsalaidbacklife) [inline client/js/store/modules/auth.js:27]: Okay now I see. Socket would keep the old cookie value from its initial connection prior to auth

File: client/js/store/modules/auth.js [hunk 5]
```diff
@@ -24,64 +52,22 @@ export default {
...
-            } else {
-              message = new Error('Unknown error signing up');
-            }
-            context.commit('clearAuth');
-            return reject(message);
-          }
-        );
-      });
+    async requestSignup(context, { username, password }) {
+      await handleLogin(context, username, password, true);
```
Comment (itsalaidbacklife) [inline client/js/store/modules/auth.js:60]: Same idea
```suggestion
    requestSignup(context, { username, password }) {
      return handleLogin(context, username, password, true);
```

File: client/js/store/modules/auth.js [hunk 6]
```diff
@@ -1,8 +1,36 @@
-import { io } from '../../plugins/sails.js';
+import { io, reconnectSockets } from '../../plugins/sails.js';
 import { ROUTE_NAME_LOBBY, ROUTE_NAME_GAME } from '@/router';
 
 import { getPlayerPnumByUsername } from '_/utils/game-utils.js';
 
+async function handleLogin(context, username, password, signup = false) {
+  const type = signup ? 'signup' : 'login';
+  try {
+    const response = await fetch(`/user/${type}`, {
```
Comment (itsalaidbacklife) [inline client/js/store/modules/auth.js:9]: nit: I think this would be more clear as `authType`
```suggestion
  const authType = signup ? 'signup' : 'login';
  try {
    const response = await fetch(`/user/${authType}`, {
```

File: client/js/store/modules/auth.js [hunk 7]
```diff
@@ -24,64 +52,22 @@ export default {
...
-              context.commit('authSuccess', data.username);
-              return resolve();
-            }
-            context.commit('clearAuth');
-            return reject(jwres.body.message);
-          }
-        );
-      });
+    async requestLogin(context, { username, password }) {
+      await handleLogin(context, username, password);
```
Comment (itsalaidbacklife) [inline client/js/store/modules/auth.js:56]: Maybe this should return so that the dispatched action can await the resulting promise. That way callers can manage loading states. I don't think this function needs to be async or to await at that point
```suggestion
    requestLogin(context, { username, password }) {
      return handleLogin(context, username, password);
```

File: client/js/store/modules/auth.js [hunk 8]
```diff
@@ -24,64 +52,22 @@ export default {
...
-        io.socket.get('/user/logout', {}, function handleResponse(resData, jwres) {
-          if (jwres.statusCode === 200) {
-            context.commit('clearAuth');
-            return resolve();
-          }
-          return reject(new Error('Error logging out :('));
+    async requestLogout(context) {
+      try {
+        await fetch('/user/logout', {
+          credentials: 'include',
```
Comment (itsalaidbacklife) [inline client/js/store/modules/auth.js:66]: I think the same applies for log out
```suggestion
        return await fetch('/user/logout', {
          credentials: 'include',
```

File: client/js/store/modules/auth.js [hunk 9]
```diff
@@ -24,64 +52,22 @@ export default {
...
         });
-      });
+      } catch (err) {
+        context.commit('clearAuth');
```
Comment (itsalaidbacklife) [inline client/js/store/modules/auth.js:69]: if so we'd throw here
```suggestion
        context.commit('clearAuth');
        throw new Error(err);
```

File: client/js/views/LoginSignup.vue [hunk 10]
```diff
@@ -126,24 +126,17 @@ export default {
...
-          })
-          .then(this.handleLogin)
-          .catch(this.handleError);
+      const action = this.isLoggingIn ? 'requestLogin' : 'requestSignup';
+      try {
+        await this.$store.dispatch(action, {
+          username: this.username,
+          password: this.pw,
+        });
+        this.handleLogin();
```
Comment (itsalaidbacklife) [inline client/js/views/LoginSignup.vue:137]: I think there's fuckery here if the store actions don't return their respective promises, which is why I suggested the above changes. I would expect `this.handleLogin()` to fire without awaiting the store dispatch b/c of the missing return. I'm less familiar with `async/await` than with `.then().catch()` but it looks like we need that return in the store actions to me

**Review by itsalaidbacklife — APPROVED** [review]
Very cool. An instructive fix worth reviewing with the team I think

File: client/js/views/LoginSignup.vue (hunk 10 above)
Comment (peterancourt) [reply client/js/views/LoginSignup.vue:137]: @itsalaidbacklife from my understanding, `this.handleLogin` will not fire until the dispatch above, and all `await`ed child calls _within_ the dispatch, wrap up execution.

As long as we are `await`ing all async calls within the dispatch:
```
// LoginSignup.vue
await this.$store.dispatch(requestLogin, {...}) 

// store/modules/auth.js (requestSignup())
await handleLogin(context, username, password, true);
...

// store/modules/auth.js (handleLogin())
const response = await fetch(`/user/${authType}`, {...})
...
return
```

then no returns should be necessary here with async/await structure! Since all async child calls from the dispatch are properly awaited, there should not be an issue with `this.handleLogin` firing prematurely

File: client/js/store/modules/auth.js (hunk 4 above)
Comment (seriouslysean) [reply client/js/store/modules/auth.js:27]: Yes, that's exactly right. By disconnecting and reconnecting we force the socket to refresh the authentication via handshake. There's probably a better way but I'm not aware of it. I know that sockets and REST calls share middleware in sails, but the reality is that the sockets don't set cookies on the browser which was causing problems.

File: client/js/views/LoginSignup.vue (hunk 10 above)
Comment (seriouslysean) [reply client/js/views/LoginSignup.vue:137]: Yep, this all tracks and I appreciate you all digging through this. We don't need these awaits as long as we're returning `this.handleLogin` since it's a promise, we're just passing it down the lane for the next bit of logic to handle. Good suggestions, thank you!

File: tests/e2e/specs/out-of-game/authentication.spec.js [hunk 11]
```diff
@@ -71,7 +71,7 @@ describe('Logging In', () => {
   /**
    * Rejected logins
    */
-  it('Rejects login before signup', () => {
+  it.only('Rejects login before signup', () => {
```
Comment (itsalaidbacklife) [inline tests/e2e/specs/out-of-game/authentication.spec.js:74]:
```suggestion
  it('Rejects login before signup', () => {
```

File: tests/e2e/specs/out-of-game/home.spec.js [hunk 12]
```diff
@@ -34,7 +34,7 @@ describe('Home - Page Content', () => {
     cy.get('[data-cy=rules-link]').click();
     cy.hash().should('eq', '#/rules');
   });
-  it('Logs user out', () => {
+  it.only('Logs user out', () => {
```
Comment (itsalaidbacklife) [inline tests/e2e/specs/out-of-game/home.spec.js:37]:
```suggestion
  it('Logs user out', () => {
```

File: client/js/views/LoginSignup.vue (hunk 10 above)
Comment (itsalaidbacklife) [reply client/js/views/LoginSignup.vue:137]: I think you're right. My comment is now handled by [this commit: ](https://github.com/cuttle-cards/cuttle/pull/124/commits/7cc7ee9d92f8d95261c1583f7fe203f724dbd707)

This line didn't itself need to change, but we just had to ensure that the actions themselves returned correctly in order to correctly `await` them here

File: tests/e2e/specs/out-of-game/authentication.spec.js (hunk 11 above)
Comment (seriouslysean) [reply tests/e2e/specs/out-of-game/authentication.spec.js:74]: God damn it
