### PR TITLE
Issue Resolves 499

### LINKED ISSUE #499: [Bug]: Discord button not responsive on mobile portrait
### Bug Summary

Discord button is not responsive on mobile portrait

### Detailed Description

The discord button in `LoginView.vue`  is not responsive on mobile portrait and the text and icon overflow. 
Screenshot_20230810-142803

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps to Reproduce

1.
2.
3.

### PR DESCRIPTION
**Pull request by haaarsh619**
Resolves #499

### CODE REVIEW

**Review by itsalaidbacklife — APPROVED** [review]
Looks good. Can you pull from main and bump the version a patch number?

File: src/views/LoginView.vue [hunk 1]
```diff
@@ -108,7 +108,8 @@
               </div>
 
               <v-btn
-                class="w-100 my-10 text-h6 h-auto py-2"
+                class="w-100 my-10  h-auto py-2"
```
Comment (Haviles04) [inline src/views/LoginView.vue:111]: I think we can use vuetifys breakpoints here `text-xs-h4`

https://vuetifyjs.com/en/styles/text-and-typography/

**Review by Haviles04 — COMMENTED** [review]
Nice!

File: src/views/LoginView.vue (hunk 1 above)
Comment (itsalaidbacklife) [reply src/views/LoginView.vue:111]: Ah yeah so this could replace the dynamic class binding below and keep the classes all together. I think that would be better

File: src/views/LoginView.vue [hunk 2]
```diff
@@ -108,7 +108,8 @@
...
+                :class="$vuetify.display.xs ? 'text-subtitle-2' : 'text-h6'"
```
Comment (itsalaidbacklife) [inline src/views/LoginView.vue:112]: So per @Haviles04 's suggestion we'd have
```suggestion
                class="w-100 my-10  h-auto py-2 text-subtitle-2 text-md-h6"
```
Which we'd then likely need to lint for line length. @haaarsh619 I think this is nicer

**Review by itsalaidbacklife — COMMENTED** [review]
Requesting refactoring to leverage Vuetify typography breakpoint classes and remove the dynamic style binding

File: src/views/LoginView.vue (hunk 1 above)
Comment (haaarsh619) [reply src/views/LoginView.vue:111]: oh i tried this but i forgot it have mobile first approach and i did something like  this,
```
text-h6  text-xs-subtitle-2 
```
 and this wont work but now i get it what was my  mistake. 
 thanks i will implement you suggestion.

**Review by itsalaidbacklife — APPROVED** [review]
