### PR TITLE
Fix issue #[514] - I added a component base menu and replaced v-menu …

### LINKED ISSUE #514: [Feature]: Create `BaseMenu` component to give all menus a consistent look and feel
### Feature Summary

We use menus in various areas of the application -- they would look more consistent with the rest of the app if we defined a `BaseMenu` to give them consistent background and text colors.

### Detailed Description

Specifically, the `BaseMenu` should accept the same default and activator slots and should use the background "cream" color of `'surface-2'` and then the "chocolate" text color of `'surface-1'`. We should then update the existing uses of `v-menu`, namely `StatsLeaderboardCell`, `GameMenu`, `ScoreGoalToolTip`, `SpectatorListMenu` so they use use this new `BaseMenu` component and the theme styles of chocolate and cream.

### PR DESCRIPTION
**Pull request by Jozemberg**
…with it

## Issue number

Relevant [514](https://github.com/cuttle-cards/cuttle/issues/514)
- Resolves #514

## Please check the following

- [YES] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [YES] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [NO] Have tests been added to cover any new features or fixes?
  - [NO] Has the documentation been updated accordingly?

### CODE REVIEW

File: src/components/BaseMenu.vue
Comment (itsalaidbacklife) [inline src/components/BaseMenu.vue:1]: This is great! I actually just created a BaseMenu component in #1275, but I left this issue open because I didn't implement consuming it in every page the way you're now doing.

So we shouldn't need this specific file but the rest of the places you're instantiating a BaseMenu should be correct (with the exception perhaps of fixing imports to grab from src/components/BaseMenu.vue)

File: src/components/BaseMenu.vue [hunk 1]
```diff
@@ -0,0 +1,45 @@
+<template>
+  <v-menu
+    v-model="internal"
+    v-bind="$attrs"
```
Comment (itsalaidbacklife) [inline src/components/BaseMenu.vue]: That said I think I forgot to bind `$attrs; would you mind adding this to the existing BaseMenu?

File: src/routes/game/components/ScoreGoalToolTip.vue [hunk 2]
```diff
@@ -28,15 +28,19 @@
...
 </template>
 
 <script>
+import BaseMenu from '_/src/components/BaseMenu.vue';
 import { useI18n } from 'vue-i18n';
 
 export default {
   name: 'ScoreGoalTooltip',
+  components: {
+    BaseMenu,  // ← ADD THIS
```
Comment (itsalaidbacklife) [inline src/routes/game/components/ScoreGoalToolTip.vue]:
```suggestion
    BaseMenu,
```

File: src/routes/game/components/SpectatorListMenu.vue
Comment (itsalaidbacklife) [inline src/routes/game/components/SpectatorListMenu.vue:1]: Looks like this is missing an import of the BaseMenu

File: src/routes/stats/components/StatsLeaderboardCell.vue
Comment (itsalaidbacklife) [inline src/routes/stats/components/StatsLeaderboardCell.vue:1]: Needs to import BaseMenu

File: src/components/BaseMenu.vue
Comment (Jozemberg) [reply src/components/BaseMenu.vue:1]: Hello, sorry for the late response. You mean that the BaseMenu component itself is redundant ? Ill fix the imports.

**Review by itsalaidbacklife — APPROVED** [review]
