### PR TITLE
Fix/three and maybe five logs

### LINKED ISSUE #1206: [Bug]: ResolveThree game log (`get-log.js`) gets the player backwards
### Bug Summary

The game history `api/helpers/game-states/get-log.js` seems to have the incorrect username for resolve 3 and resolve 5 moveTypes and possibly others

### Detailed Description

We should look at this method's use of player and opponent

### Current Behavior

It displays the opponent of the person who gets the benefit instead of the player themselves

### Expected Behavior

The player who played the 3/5's username appears in the log for the resolveThree or resolveFive move log

### Steps to Reproduce

1. Play a 3 or 5 as player 1
2. Resolve it as player 2
3. pick the card to get/discard as player 1
4. Read the log. Should say "player 1..." but instead says "player 2..."

### PR DESCRIPTION
**Pull request by itsalaidbacklife**
Fixes bugs in the game log for one-off resolutions and adds test assertions to check the log output for the moves in question

## Issue number

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #1206 

## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [ ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

### CODE REVIEW

File: api/helpers/game-states/get-log.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ module.exports = {
       };
 
       const player = game[`p${row.playedBy}`]?.username;
-      const opponent = game[`p${row.playedBy % 2}`]?.username;
+      const opponent = game[`p${(row.playedBy + 1) % 2}`]?.username;
```
Comment (itsalaidbacklife) [inline api/helpers/game-states/get-log.js:30]: There were two main bugs:
1. Incorrectly computing the opponent here
2. Switching player and opponent below for one-off resolution because the person who triggers the resolution step is the opponent of the person who played the oneOff

File: tests/unit/fixtures/gameStates/resolveNine.js
Comment (itsalaidbacklife) [inline tests/unit/fixtures/gameStates/resolveNine.js:1]: This one was kinda mixed up across the board. The card was clearly in p1's hand so it should be asserting that p1 got the card and set playedBy since they wee the one the one who resolved (by declining to counter)

**Review by itsalaidbacklife — COMMENTED** [review]
This should clean up the logs
