### PR TITLE
Fix/5 discard same card

### LINKED ISSUE #901: [Bug]: Playing multiple 5's allows you to skip discarding
### Bug Summary

Playing a 5 doesn't correctly clear out the card seleted for discard such that playing a second 5 allows you to cheat by not discarding.

### Detailed Description

Playing a 5 requires the player to discard a card, then draw 3, but the dialog is bugged to allow you to "discard" the card you discarded last time even if it's not in your hand.

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps to Reproduce

1. Play a 5
2. Play a second 5 and hit "Discard and draw" without selecting a new card for discard
3. You'll draw 3 cards without discarding

### PR DESCRIPTION
**Pull request by itsalaidbacklife**
## Issue number

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #901 

## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [ ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

### CODE REVIEW

File: src/routes/game/components/dialogs/components/FiveDialog.vue [hunk 1]
```diff
@@ -47,14 +47,20 @@ const { player } = storeToRefs(gameStore);
...
 const dialog = computed(() => t(player.value.hand.length ? 'game.dialogs.five.resolveFive' : 'game.dialogs.five.resolveFiveNoCards'));
 const buttonText = computed(() => t(player.value.hand.length ? 'game.dialogs.five.discardAndDraw' : 'rules.draw'));
 
 const selectCard = (index) => {
   selectedCard.value = player.value.hand[index].id;
 };
+
+function resolveFive() {
+  emit('resolve-five', selectedCard.value);
+  selectedCard.value = null;
```
Comment (itsalaidbacklife) [inline src/routes/game/components/dialogs/components/FiveDialog.vue:61]: This is what clears out state so that the next time the FiveDialog doesn't allow you to "discard" the same card and skip discarding

File: src/routes/game/components/dialogs/components/FiveDialog.vue [hunk 2]
```diff
@@ -47,14 +47,20 @@ const { player } = storeToRefs(gameStore);
 const selectedCard = ref();
 const emit = defineEmits(['resolve-five']);
 
-const disableButton = computed(() => !player.value.hand.length || !selectCard.value);
+const disableButton = computed(() => player.value.hand.length && !selectedCard.value);
```
Comment (itsalaidbacklife) [inline src/routes/game/components/dialogs/components/FiveDialog.vue:50]: The computed prop for disabling the button was bugged so that it wasn't disabled when you'd failed to select a card. I also clarified its logic here by removing negations. 

The button should be disabled if you have cards in your hand but haven't selected one for discard

File: src/routes/game/components/dialogs/components/FiveDialog.vue [hunk 3]
```diff
@@ -22,8 +22,8 @@
         color="surface-1"
         variant="flat"
         data-cy="submit-five-dialog"
-        :disabled="!disableButton"
-        @click="emit('resolve-five', selectedCard)"
+        :disabled="disableButton"
```
Comment (itsalaidbacklife) [inline src/routes/game/components/dialogs/components/FiveDialog.vue:25]: Easier to read when the attribute binding doesn't have !
