### PR TITLE
Fix/scuttle animation - fixes #301

### LINKED ISSUE #301: [Bug]: Scuttle Animation doesn't display scuttling card
### Bug Summary

When a point card is scuttled, the card played to scuttle it appears on top of the card, then both animate to the left, towards the scrap. Currently the scuttling card image does not render correctly and we see the missing image icon + alt text

### Detailed Description

It currently looks like this:
image

Where the scuttling card is displayed with the the missing image placeholder icon. We should look at the GameCard.vue component, where this image is rendered, to resolve the issue

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps to Reproduce

1. Start up a game
2. Play points as one player
3. Have opponent scuttle the point card
4. Both will see the placeholder for a missing image appear on top of the scuttled card before it is scrapped

### PR DESCRIPTION
**Pull request by itsalaidbacklife**
## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change
Fixes the transition classes and the image on the scuttling card

### CODE REVIEW

File: src/views/GameView.vue [hunk 1]
```diff
@@ -1052,19 +1052,19 @@ export default {
   position: absolute;
 }
 // slide-below (enter and leave below)
-.slide-below-enter,
+.slide-below-enter-from,
```
Comment (itsalaidbacklife) [inline src/views/GameView.vue:1055]: Vue3 changed the initial frame class to .enter-from: https://vuejs.org/guide/built-ins/transition.html#css-based-transitions

Comment (seriouslysean) [reply src/views/GameView.vue:1055]: Ahhhh I knew it! Good stuff!

**Review by seriouslysean — APPROVED** [review]
