### PR TITLE
chooseWeatherToCounter message split in two t() functions

### LINKED ISSUE #882: [Bug]: Missing/Incorrect translation key in `ChooseWhetherToCounterDialog` for targeted one-off case
### Bug Summary

The ChooseWhetherToCounter dialog incorrectly shows "game.dialogs.counterDialogs.target.global.your" instead of the words "targeting your"

### Detailed Description

See image:
image

The text here should instead read: Your opponent has played the 9♦️ targeting your J♠️. The issue is line 9 of `ChooseWhetherToCounterDialog` which incorrectly uses a single `t()` call for two separate strings instead of two:
```
{{ t('game.dialogs.counterDialogs.target' + 'global.your') }}
```

### Current Behavior

The dialog fails to translate the 'targeting your' text

### Expected Behavior

The text is correctly rendered/translated

### Steps to Reproduce

1.
2.
3.

### PR DESCRIPTION
**Pull request by Posoroko**
## 882

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #882

## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [ ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

Created two t() functions to fix the display problem.

### CODE REVIEW

File: src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue [hunk 1]
```diff
@@ -27,12 +27,7 @@
         </p>
         <div v-if="target" id="target-wrapper">
           <span id="target-icon-wrapper" class="d-flex justify-center align-center">
-            <v-icon
-              size="x-large"
-              color="red"
-              icon="mdi-target" 
-              aria-hidden="true"           
-            />
+            <v-icon size="x-large" color="red" icon="mdi-target" aria-hidden="true" />
```
Comment (itsalaidbacklife) [inline src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue:30]: This is causing the lint failure. We have Vue/max-attributes-per-line set to 3. Please roll this back to the previous format. It looks like you may have a local editor config conflicting with the project lint config

File: src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue [hunk 2]
```diff
@@ -41,21 +36,10 @@
...
         {{ t('game.dialogs.counterDialogs.counter') }}
       </v-btn>
-      <v-btn
-        data-cy="decline-counter-resolve"
-        color="surface-1"
-        variant="flat"
-        class="ml-4"
-        @click="resolve"
-      >
+      <v-btn data-cy="decline-counter-resolve" color="surface-1" variant="flat" class="ml-4" @click="resolve">
```
Comment (itsalaidbacklife) [inline src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue:42]: Same for these

**Review by itsalaidbacklife — APPROVED** [review]
Nice one. The fix looks good but some extraneous formatting changes are causing lint errors

File: src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue [hunk 3]
```diff
@@ -41,19 +41,18 @@
...
-      <v-btn
-        data-cy="decline-counter-resolve"
-        color="surface-1"
-        variant="flat"
-        class="ml-4"
+      <v-btn 
+        data-cy="decline-counter-resolve" 
+        color="surface-1" 
+        variant="flat" 
+        class="ml-4"
```
Comment (itsalaidbacklife) [inline src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue:55]: Whitespace
```suggestion
      <v-btn 
        data-cy="decline-counter-resolve"
        color="surface-1"
        variant="flat"
        class="ml-4"
```

**Review by itsalaidbacklife — COMMENTED** [review]
Almost there. Try running `npm run lint:fix` to address the last problem (plus the whitespace)

File: src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue [hunk 4]
```diff
@@ -27,11 +27,11 @@
         </p>
         <div v-if="target" id="target-wrapper">
           <span id="target-icon-wrapper" class="d-flex justify-center align-center">
-            <v-icon
+            <v-icon
```
Comment (itsalaidbacklife) [inline src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue:30]:
```suggestion
            <v-icon
```

File: src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue [hunk 5]
```diff
@@ -41,15 +41,15 @@
...
 
     <template #actions>
-      <v-btn
-        data-cy="counter"
-        color="newPrimary"
-        variant="flat"
+      <v-btn 
+        data-cy="counter" 
+        color="newPrimary" 
+        variant="flat"
```
Comment (itsalaidbacklife) [inline src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue:47]:
```suggestion
        data-cy="counter"
        color="newPrimary"
        variant="flat"
```

File: src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue [hunk 6]
```diff
@@ -41,15 +41,15 @@
...
+      <v-btn 
+        data-cy="counter" 
+        color="newPrimary" 
+        variant="flat" 
         @click="$emit('choose-to-counter')"
       >
         {{ t('game.dialogs.counterDialogs.counter') }}
       </v-btn>
-      <v-btn
+      <v-btn
```
Comment (itsalaidbacklife) [inline src/routes/game/components/dialogs/components/ChooseWhetherToCounterDialog.vue:52]:
```suggestion
      <v-btn
```
