### PR TITLE
Fix issue 430

### LINKED ISSUE #430: [DevEx]: Define generic `BaseOverlay` component to apply consistent styles to overlays throughout the app
### Improvement Summary

We have several overlays that use a consistent style including a header with a background color. We should refactor them to use a custom `BaseOverlay` component for consistency and DRYness.

### Detailed Description

Currently `src/components/GameView/GameOverlays.vue` and `src/components/GameView/GameUnavailableOverlay.vue` use the same style of overlays where the text is chocolate on a cream background. This involves duplicate css that could be consolidated through the use a new `BaseDialog.vue` component. We should define this BaseDialog with these styles and appropriate slots to fill its header and to add optional content below the header to suit the existing use cases more effieciently.

image

### PR DESCRIPTION
**Pull request by Bhcfg**
Fixes #430

## Summary
Created a reusable `BaseOverlay` component to consolidate duplicate overlay styles that were previously duplicated across multiple files.

## Changes
- **Created** `src/components/BaseOverlay.vue` - A reusable overlay component with consistent styling and slots for header and content
- **Refactored** `src/routes/game/components/GameUnavailableOverlay.vue` to use BaseOverlay
- **Refactored** `src/routes/game/components/GameOverlays.vue` to use BaseOverlay (7 overlays converted)
- **Removed** duplicate CSS from both files (36 lines of duplicate code)

## Issue number
- Resolves #430

## Please check the following
- [x] Do the tests still pass?
- [x] Is the code formatted properly?
- [x] No new features requiring new tests
- [x] No documentation changes needed

## Please describe additional details for testing this change
The BaseOverlay component consolidates styling from existing overlays. All overlay functionality remains the same, only the implementation changed. To test:
1. Start a game and trigger various overlays (waiting for game to start, opponent actions, etc.)
2. Verify overlays display correctly with cream background and chocolate text
3. Check that all overlay interactions work as before

### CODE REVIEW

**Review by itsalaidbacklife — DISMISSED** [review]
Thank you for your contribution!

File: src/components/BaseOverlay.vue [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+      type: Boolean,
+      required: true,
+    },
+    persistent: {
+      type: Boolean,
+      default: false,
+    },
+  },
+};
+</script>
```
Comment (itsalaidbacklife) [inline src/components/BaseOverlay.vue]: Let's refactor this to script setup
```suggestion
<script setup>
defineOptions({
  name: 'BaseOverlay',
  inheritAttrs: false,
});

const _props = defineProps({
  modelValue: {
    type: Boolean,
    required: true,
  },
  persistent: {
    type: Boolean,
    default: false,
  },
});
</script>
```

**Review by itsalaidbacklife — APPROVED** [review]
