### PR TITLE
Fix/prevent joining closed games

### LINKED ISSUE #346: [BUG]: Backend allows subscribing to closed games
### Bug Summary

When a game becomes full (has 2 players) the frontend disables the join button for that game, but the backend still accepts requests to subscribe to it

### Detailed Description

The /game/subscribe endpoint makes no check that the game is open for players to join. Currently users are prevented from subscribing to games client side, but we should also prevent this on the backend.

Basically this endpoint should query for the game being requested *before* subscribing you to it, and should return a badRequest response if that game has a `status === false` or if the number of players it has is > 1. 

The frontend should then show a snackbar when this error occurs 

### Current Behavior

If you remove the `disabled` prop from the join button in `GameListItem.Vue` and create a game, join it as two players then try to join it as a third player, it will bring the new player to the lobby of the game and add them to the list of players, causing weird effects in the game.

### Expected Behavior

When a user attempts to join a game that’s closed or that has two players in it already, the backend should throw an error that’s displayed in a snackbar to the user saying “Oops, that game is already full”

### Steps to Reproduce

1. Remove the `disabled` prop from `GameListItem.Vue`
2. Start the front and back ends, sign up three accounts in three separate browsers
3. Create a game, and join it as two players
4. Join it as the third player and you will be incorrectly brought to the lobby

### PR DESCRIPTION
**Pull request by itsalaidbacklife**
## Please check the following
Resolves #346 by throwing backend error when subscribing to game that's already full. Added appropriate assertions to the relevant test case.

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle#linting-formatting))
- For New Features:
  - [x] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change
Throw an error when request to subscribe is made on a full game, disable the join button and add display a snackbar error
image

### CODE REVIEW

File: src/store/modules/game.js [hunk 1]
```diff
@@ -326,7 +326,8 @@ export default {
               });
               return resolve();
             }
-            return reject(new Error('error subscribing'));
+            const message = res.message ?? 'error subscribing';
+            return reject(new Error(message));
```
Comment (itsalaidbacklife) [inline src/store/modules/game.js:330]: Updated to show specific error message if it is available

File: tests/e2e/specs/out-of-game/home.spec.js [hunk 2]
```diff
@@ -148,6 +149,18 @@ describe('Home - Game List', () => {
 
       // Test that join button is now disabled
       cy.contains('[data-cy-join-game]', 'Play').should('be.disabled');
+
+      // Manually re-enable join button to confirm backend rejects request
+      cy.window().its('cuttle.app.config.globalProperties.$store')
+        .invoke('commit', 'updateGameStatus', {id: gameData.gameId, newStatus: true});
```
Comment (itsalaidbacklife) [inline tests/e2e/specs/out-of-game/home.spec.js:155]: I spent a while trying to figure out how to test this issue. I tried having the test directly 
```
.invoke('dispatch', 'requestSubscribe', {id: gameData.gameId})
```

But I had trouble managing the promises to make the test pass if we got the expected error and fail otherwise. Plus that doesn't confirm that the snackbar shows up displaying the error message. I thought about disconnecting and reconnecting the socket so the player misses that the game is over, but that's a bit brittle because eventually we'd like the socket reconnect logic to rehydrate the list of which games are available.

Eventually I settled on having the test code manually switch a game to `status: true` by invoking the store mutation directly here. I'm really pleased with how this turned out because it lets the test control the game looking 'available' on the clientside without weird backend implications and then the actual interactions and assertions (clicking the button then asserting the button disables and the snackbar appears) happen organically through the app as usual

File: api/controllers/game/subscribe.js [hunk 3]
```diff
@@ -15,6 +15,12 @@ module.exports = function (req, res) {
     .then(async function success(arr) {
       // Catch promise values
       const [game, user] = arr;
+
+      // Fast fail if game is full
+      const gameIsFull = !game.status || game.players.length >= 2 || game.log.length > 0;
```
Comment (seriouslysean) [inline api/controllers/game/subscribe.js:20]: I feel like this should be moved to a helper function if you’ll need it in more than one place ever. It could take game as an argument.

File: api/controllers/game/subscribe.js [hunk 4]
```diff
@@ -15,6 +15,12 @@ module.exports = function (req, res) {
...
+      if (gameIsFull) {
+        throw { message: `Cannot join that game because it's already full` };
+      }
```
[the remark this answers is not in the document]
Comment (seriouslysean) [reply api/controllers/game/subscribe.js:23]: Is it worth walking through each way a game could be considered full? Or possibly updating the logic to better track when a game is full? Could even add a few second delay before folks are able to join a game but that seems kinda weird.

I’m not too familiar with how quickly everything updates though.

File: src/views/HomeView.vue [hunk 5]
```diff
@@ -35,7 +35,7 @@
                       :status="game.status"
                       :num-players="game.numPlayers"
                       :is-ranked="game.isRanked"
-                      @error="handleError"
+                      @error="handleSubscribeError(game.id, $event)"
```
Comment (seriouslysean) [inline src/views/HomeView.vue:38]: You’re sending the event but then calling it message in the method? That seems kind of confusing to me.

**Review by seriouslysean — APPROVED** [review]
This seems fine to me, just a few questions.

File: api/controllers/game/subscribe.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (itsalaidbacklife) [reply api/controllers/game/subscribe.js:23]: I definitely want to update the logic to better track when a game is full. That's essentially #374, which would hopefully make this more water tight. For now I think this is as specific as we can get with the data that's currently stored.

File: api/controllers/game/subscribe.js (hunk 3 above)
Comment (itsalaidbacklife) [reply api/controllers/game/subscribe.js:20]: Pulled into a new synchronous `isGameFull(game)` helper

File: src/views/HomeView.vue (hunk 5 above)
Comment (itsalaidbacklife) [reply src/views/HomeView.vue:38]: So the event payload is the error message. It seemed more descriptive for the method argument to describe what the event is rather than just calling it `$event` inside of `handldeSubscribeError()`. Do you disagree? Do you think we should call it `$event` in both places?

We're stuck using $event in the event handler here in the html, so if we want them to be the same I would think we'd have to call both of them `$event`. But isn't it more clear to have the method argument say what the event _is_?

Comment (itsalaidbacklife) [reply src/views/HomeView.vue:38]: Is it the name `message` that's specifically confusing? Would it be better as `errMessage`?
