### PR TITLE
flex and align-center classes added to the v-witch

### LINKED ISSUE #772: [Bug]: Create Game Dialog ranked switch + button vertical alignment is off-center
### Bug Summary

The switch in the `CreateGameDialog` is vertically top-aligned instead of centered

### Detailed Description

See pic
image

We should adjust the container with the button to vertically center the contents. This should have been achieved already using `class="d-flex align-center"` on the parent element of the `v-switch`, so we'll need to investigate and debug

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps to Reproduce

1.
2.
3.

### PR DESCRIPTION
**Pull request by Posoroko**
## #772

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #772

## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [ ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change
I added
```
class="d-flex align-center"
```
on the v-switch.  The same classes were already applied to the form parent element, but the v-switch has a container div that needs to be vertically align as well.
There might be a more 'vuetify-ish' way of handleing this ?

the v-swith component has a center-affix prop:
image

It's true by default, so I thaought it would be centering its content, but maybe I misunderstand this...

### CODE REVIEW

File: src/routes/home/components/CreateGameDialog.vue [hunk 1]
```diff
@@ -36,6 +36,7 @@
         />
         <v-switch
           v-model="isRanked"
+          class="d-flex align-center"
```
Comment (itsalaidbacklife) [inline src/routes/home/components/CreateGameDialog.vue:39]: Does this actually fix the issue? Can I get a before/after screenshot?

Comment (Posoroko) [reply src/routes/home/components/CreateGameDialog.vue:39]: yep :
with flex
without flex

Comment (Posoroko) [reply src/routes/home/components/CreateGameDialog.vue:39]: yep, it seems to be fixing it :
with flex
without flex

**Review by itsalaidbacklife — APPROVED** [review]
