### PR TITLE
bug/446 Close buttons have wrong style in TargetingOverlay

### LINKED ISSUE #446: [Bug]: Close buttons have wrong style in TargetingOverlay, RulesDialog, and ScrapDialog
### Bug Summary

We frequently use an “X” button in dismissible dialogs and overlays, and several of them have incorrect styles 

### Detailed Description

The ScrapDialog, TargetSelectionOverlay, and RuleaDialog all have the incorrect button styles for this X button. They should look like the X in the MoveChoiceOverlay: no background color and an X icon. Instead they have a white background, and the TargetSelectionOverlay specifically has no icon visible.

To fix it we should revise the close buttons in these components to match the style from the MoveChoiceOverlay

### Current Behavior

They currently look like this
IMG_4491

IMG_4490
IMG_4489

### Expected Behavior

They should look like this
IMG_4492

### Steps to Reproduce

1.
2.
3.

### PR DESCRIPTION
**Pull request by kawaljen**
## 446

Relevant 446(https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #446

## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [ ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change
the issue mentionned ScrapDialog and RuleaDialog but i find that this issue has been already resolved when the design have been updated

### CODE REVIEW

**Comment by kawaljen** [comment]
the issue mentionned ScrapDialog and RuleaDialog but i find that this issue was already resolved when the design have been updated

**Review by itsalaidbacklife — APPROVED** [review]
Nice work. Can you additionally update the v-btn in RulesDialog to have variant="text" so that button loses its background color?

I think it's fine to keep the background color as we have it for the targeting overlay to ensure sufficient contrast, but RulesDialog stands out as the only dialog with a background color on the close button so it'd be more consistent to fix it

**Comment by kawaljen** [comment]
ok the button the RuleaDialog is updated

File: src/routes/game/components/dialogs/components/RulesDialog.vue [hunk 1]
```diff
@@ -2,12 +2,17 @@
   <BaseDialog id="rulesDialog" max-width="1250">
     <template #title>
       <h1>Rules of Cuttle</h1>
-      <v-btn icon aria-label="Close rules dialog" @click="close">
+      <v-btn
+        icon 
+        aria-label="Close rules dialog"
+        color="surface-1"
```
Comment (itsalaidbacklife) [inline src/routes/game/components/dialogs/components/RulesDialog.vue:8]: Rather than setting the color prop to the same color as the background, let's set the `variant` prop to "text" in order to set the button style to not have a background at all.
```suggestion
        color="surface-2"
        variant="text"
```


I believe this should make it so the icon appears the "cream" color but without a background

**Review by itsalaidbacklife — COMMENTED** [review]
Thank you; this is super close. Can you make it so the button has the text style in the rules dialog and adjust the color so the button is cream colored since it displays on a "chocolate" background if I remember correctly.

Please correct me if I'm wrong but I think the background of the dialog will be chocolate so we want the button to have a lighter color. Can you please also comment a screenshot of each button that we can use for the patch note?

File: src/routes/game/components/dialogs/components/RulesDialog.vue (hunk 1 above)
Comment (kawaljen) [reply src/routes/game/components/dialogs/components/RulesDialog.vue:8]: Sure, so let me paste screenshots of all the close buttons I found to be sure all is good

Comment (kawaljen) [reply src/routes/game/components/dialogs/components/RulesDialog.vue:8]: On src/routes/game/components/MoveChoiceOverlay.vue

that button was set to have a white color property, I believe it should be cream too

Screenshot from 2024-02-11 14-51-54

Comment (kawaljen) [reply src/routes/game/components/dialogs/components/RulesDialog.vue:8]: On the src/components/BaseSnackbar.vue

No change needed , the background color is already transparent

Screenshot from 2024-02-11 14-49-30

Comment (kawaljen) [reply src/routes/game/components/dialogs/components/RulesDialog.vue:8]: On src/routes/game/components/TargetSelectionOverlay.vue

white background, to keep contrast as you mentionned

Screenshot from 2024-02-11 12-56-41

Comment (kawaljen) [reply src/routes/game/components/dialogs/components/RulesDialog.vue:8]: On src/routes/game/components/dialogs/components/ScrapDialog.vue

Brown background (just like RulesDialog.vue) so I add variant="text" and remove elevation="0"

Screenshot from 2024-02-11 11-44-00

Comment (kawaljen) [reply src/routes/game/components/dialogs/components/RulesDialog.vue:8]: and the src/routes/game/components/dialogs/components/RulesDialog.vue

Which is now cream and without background
Screenshot from 2024-02-11 11-42-39

**Review by itsalaidbacklife — APPROVED** [review]
Excellent; thank you!
