### PR TITLE
Bug #538 spectator list menu colors

### LINKED ISSUE #538: [Bug]: SpectatorListMenu background and font colors are incorrect
### Bug Summary

The SpectatorListMenu which shows the list of players spectating a game should have a cream background (`surface-2` in the vuetify theme) and chocolate colored text (`surface-1`). Instead it has a cream border, white background, and black text

### Detailed Description

See image below:
image

It should instead have the same colors as the `GameMenu` next to it:
image

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps to Reproduce

1. Join a game
2. Click the 'eye' menu to list the spectators

### PR DESCRIPTION
**Pull request by Haviles04**
## Issue number

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #538 

## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

- Updated color props in v-list item

image
image

### CODE REVIEW

File: src/components/GameView/SpectatorListMenu.vue [hunk 1]
```diff
@@ -21,12 +21,10 @@
       bg-color="surface-2"
       data-cy="spectate-list-menu"
     >
-      <v-list v-if="spectatingUsers.length > 0">
+      <v-list v-if="spectatingUsers.length > 0" color="surface-1" bg-color="surface-2">
```
Comment (itsalaidbacklife) [inline src/components/GameView/SpectatorListMenu.vue:24]: Looking at this again, why do we have 2 v-lists nested here? It looks like the inner one here is only used in order to conditionally render the list of spectators. Can we just replace this with a template tag?
```suggestion
      <template v-if="spectatingUsers.length > 0">
```

Comment (Haviles04) [reply src/components/GameView/SpectatorListMenu.vue]: Good call, I readjusted the html.

**Review by itsalaidbacklife — APPROVED** [review]
