### PR TITLE
Bug #794 Flaky spectate test

### LINKED ISSUE #794: [Bug]: `it('spectates a game')` test fails flakily sometimes
### Bug Summary

One of the tests in `tests/e2e/in-game/spectating.spec.js` fails randomly sometimes

### Detailed Description

The first test in the `spectating.spec` has been failing randomly:
```
it('Spectates a game', () => {
```

Here is an example test run: https://cloud.cypress.io/projects/i8bxr8/runs/2d121cf6-4a2c-439f-b463-215cb3d6483e/test-results/969394b4-b389-494f-a781-31ebe89f906b/replay?ts=1700497544242.2686&att=1

It appears to be the case that after the `cy.reload()` the DOM shows the `GameUnavailableView`

We should investigate why and fix the test and/or app so that it behaves correctly

### Current Behavior

The `'spectates a game'` test sometimes fails randomly

### Expected Behavior

The test should consistently pass

### Steps to Reproduce

It can't be consistently reproduced, but

### PR DESCRIPTION
**Pull request by Haviles04**
## Issue number

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #794 

## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [ ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

Added router check to `isSpectating` computed value in `GameView.vue` to check after reload

### CODE REVIEW

File: src/routes/game/GameView.vue [hunk 1]
```diff
@@ -472,7 +472,7 @@ export default {
     ...mapStores(useGameStore),
     ...mapStores(useAuthStore),
     isSpectating() {
-      return this.gameStore.isSpectating;
+      return this.gameStore.isSpectating || this.$router.currentRoute.value.name === ROUTE_NAME_SPECTATE;
```
Comment (itsalaidbacklife) [inline src/routes/game/GameView.vue:475]: Do we want both the store value and the route or should we update the consumers of the store value to use the router instead?

**Review by itsalaidbacklife — COMMENTED** [review]
Good catch. One question: should we still use the store value at all or replace it altogether with the route check?

**Comment by Haviles04** [comment]
> Good catch. One question: should we still use the store value at all or replace it altogether with the route check?

We still need the store value inside the store, this way updateGame knows we are spectating.

Without it, when you join a game from the lobby it doesn't sort the top cards because the name is home


Inside the `GameView.vue` we can just use the route

File: src/routes/game/GameView.vue (hunk 1 above)
Comment (seriouslysean) [reply src/routes/game/GameView.vue:475]: If the store value can be derived from the route it might make sense to keep both so you have one setter and all consumers use the store since that’s typically easier to check in the code.

**Comment by seriouslysean** [comment]
@Haviles04 @itsalaidbacklife i don’t think a getter has access to route, but you can add some logic when entering or exiting the route to dispatch an action. Might take some tinkering, there’s some interesting cases between resetting before each, etc.

Give it a crack and see where you land. I’m busy most of today, but can take a look tomorrow morning.

File: src/stores/auth.js [hunk 2]
```diff
@@ -110,6 +111,13 @@ export const useAuthStore = defineStore('auth', {
         //     - `gameService.populateGame` is called
         //     - `Game.subscribe` is called
         //     - `Game.publish` is called
+
+        const gameStore = useGameStore();
+        if (!gameId && isSpectating) {
+          let { gameId } = route.params;
```
Comment (itsalaidbacklife) [inline src/stores/auth.js:117]: should be const if we're not modifying this
```suggestion
          const { gameId } = route.params;
```

File: src/stores/auth.js [hunk 3]
```diff
@@ -110,6 +111,13 @@ export const useAuthStore = defineStore('auth', {
...
+          gameStore.requestSpectate(Number(gameId));
+        }
+
         if (gameId && (isGame || isLobby)) {
           const gameStore = useGameStore();
```
Comment (itsalaidbacklife) [inline src/stores/auth.js:122]: Let's remove this since we're now declaring gameStore above
```suggestion
```
