### PR TITLE
fix: reorganized components

### LINKED ISSUE #546: [DevEx]: Reorganize Vue components
### Improvement Summary

In order to make it easier to find the any given component, we should groups components into subdirectories based on which page(s) they are used in

### Detailed Description

Currently most of the components in `src/components` are “loose” in the components folder and not grouped into subdirectories. We should create one subdirectory per page (for pages that have dedicated components):

`src/components/HomeView`
`src/components/StatsView`
`src/components/RulesView`
`src/components/LobbyView`
(Note we already have `src/components/GameView`)

and place the relevant components into the subdirectory for the page in which they appear. All the Stats… components should go in StatsView, etc. We can leave the global navigation components in the root `src/components` folder for now as there aren’t many of them, and they are globally scoped to the entire application.

### PR DESCRIPTION
**Pull request by arnaut08**
## Issue number #546

Relevant #546
- Resolves #546

## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change
I don't think additional details are required as it's just the reorganization of the components files.

### CODE REVIEW

**Review by seriouslysean — CHANGES_REQUESTED** [review]
Solid work so far! I think this is headed mostly in the right direction but I have a lot of thoughts on how I think we should be separating everything.

Considering how we utilize the components, it makes sense to me to split by route for now, and then organizing within route based folders.

Something like this:

/routes/

    - /home/
        - /components
        - /js
    - /about/
        - /components
        - /js

Etc, which would allow us to code split by route if we so choose by doing async imports. It also would keep a logical separation of components we use within those pages and would could set up route based aliases in vite. Any shared functionality would live under some sort of core, or global namespace.

@itsalaidbacklife penny for your thoughts.

**Comment by arnaut08** [comment]
> Considering how we utilize the components, it makes sense to me to split by route for now, and then organizing within route based folders.
> 
> Something like this:
> 
> * /routes/
>   
>   * /home/
>     
>     * /components
>     * /js
>   * /about/
>     
>     * /components
>     * /js

Currently we have all the views(route specific files) inside the /views directory. As per my understanding, you're asking for us to split the files as per the routes. So we'll have a /routes directory and individual directories for each route with respective view file, and respective components grouped in the components directory, right? 
Something like this:
- Main view file - /routes/home/HomeView.vue
- Respective component files - /routes/home/Components/...

Also, what exactly is the js subdirectory for? Is it for respective utility function files?

**Comment by seriouslysean** [comment]
> Also, what exactly is the js subdirectory for? Is it for respective utility function files?

@arnaut08 exactly that. Utilities, store files, or anything other js imports related to just that route. You may not need the folder if the route doesn't have any right now, though.

I'll file a follow up to look in to async importing the top level Vue files from the router to garner the benefit from the file restructure.

File: src/core/components/TheHeader.vue [hunk 1]
```diff
@@ -39,7 +39,7 @@
 </template>
 
 <script setup>
-import { getPageLinks } from '@/composables/navLink.js';
+import { getPageLinks } from '../composables/navLink.js';
```
Comment (seriouslysean) [inline src/core/components/TheHeader.vue:42]: This should stay an alias

File: src/routes/game/components/ChooseWhetherToCounterDialog.vue [hunk 2]
```diff
@@ -58,9 +58,9 @@
 </template>
 
 <script>
-import BaseDialog from '@/components/Global/BaseDialog.vue';
-import GameCard from '@/components/GameView/GameCard.vue';
-import GameCardName from '@/components/GameView/GameCardName.vue';
+import BaseDialog from '@/core/components/BaseDialog.vue';
+import GameCard from './GameCard.vue';
```
Comment (seriouslysean) [inline src/routes/game/components/ChooseWhetherToCounterDialog.vue:62]: These should stay aliases, too

File: src/routes/game/components/GameDialogs.vue [hunk 3]
```diff
@@ -46,13 +46,13 @@
...
 import { mapState } from 'vuex';
 
-import CannotCounterDialog from '@/components/GameView/CannotCounterDialog.vue';
-import CounterDialog from '@/components/GameView/CounterDialog.vue';
-import FourDialog from '@/components/GameView/FourDialog.vue';
-import GameOverDialog from '@/components/GameView/GameOverDialog.vue';
-import ReauthenticateDialog from '@/components/GameView/ReauthenticateDialog.vue';
-import SevenDoubleJacksDialog from '@/components/GameView/SevenDoubleJacksDialog.vue';
-import ThreeDialog from '@/components/GameView/ThreeDialog.vue';
+import CannotCounterDialog from './CannotCounterDialog.vue';
```
Comment (seriouslysean) [inline src/routes/game/components/GameDialogs.vue:49]: These should stay aliases

File: src/routes/game/components/GameUnavailableView.vue [hunk 4]
```diff
@@ -12,7 +12,7 @@
 </template>
 
 <script>
-import ReauthenticateDialog from '@/components/GameView/ReauthenticateDialog.vue';
+import ReauthenticateDialog from './ReauthenticateDialog.vue';
```
Comment (seriouslysean) [inline src/routes/game/components/GameUnavailableView.vue:15]: Keep as alias

File: src/routes/game/components/GameUnavailableView.vue [hunk 5]
```diff
@@ -12,7 +12,7 @@
...
 import GameUnavailableOverlay from './GameUnavailableOverlay.vue';
```
Comment (seriouslysean) [inline src/routes/game/components/GameUnavailableView.vue:16]: Convert to alias

**Review by seriouslysean — CHANGES_REQUESTED** [review]
This is super close! Convert  all the relative paths to aliases and in the vite config make an entry for the new areas; core, and each route as a top level so you can do something like `~core/components/FileName.Vue`.

**Comment by itsalaidbacklife** [comment]
@arnaut08 sorry to have left this hanging. This is looking good. I need to sync up with @seriouslysean and give this a look together but we should have the final feedback for you by end of week

**Comment by arnaut08** [comment]
Sorry for the delayed response. I've made the changes suggested by @seriouslysean. Please review those changes and consider them for the feedback. Thank you.

File: src/routes/game/components/SevenDoubleJacksDialog.vue [hunk 6]
```diff
@@ -45,8 +45,8 @@
 </template>
 
 <script>
-import BaseDialog from '@/components/Global/BaseDialog.vue';
-import GameCard from '@/components/GameView/GameCard.vue';
+import BaseDialog from '~core/components/BaseDialog.vue';
+import GameCard from './GameCard.vue';
```
Comment (itsalaidbacklife) [inline src/routes/game/components/SevenDoubleJacksDialog.vue:49]: Let's stick to imports from `'@'` for flexibility in case files are moved around

**Review by itsalaidbacklife — COMMENTED** [review]
This is a great start. I apologize that it's taken so long to get a full review on this. It's a high impact restructuring so we wanted to make sure the internal team was in sync about the desired structure. I'm requesting a slight rework of how the folders are organized, and of removing the `~` aliases and sticking with `@` relative imports.

For the folder change, we will remove the `core` folder, and move both `core/components` and `core/composables` directly into `src/components` (for base components) and `src/composables` (for root composables).

Additionally, let's rename the `src/routes/auth` folder to `src/routes/login` as that's the name of the route. 

Again, great work! This will add a lot of value, especially making it easier for new contributors to find components while onboarding. Thanks for your contribution! Please comment here (or join us on [discord](https://discord.gg/6vQCFa6nvP)) if you have any questions.

**Comment by itsalaidbacklife** [comment]
@arnaut08 are you still interested in finishing this task?

**Comment by arnaut08** [comment]
> @arnaut08 are you still interested in finishing this task?

Hey! I'm so sorry for the delayed response. Yes, I'll make the changes as per your latest comments.

File: src/core/components/UsernameToolTip.vue
[the remark this answers is not in the document]
Comment (arnaut08) [reply src/core/components/UsernameToolTip.vue:1]: This is being imported in `UsernameToolTip.stories.js` as well. Should I keep it in the `src/components` only or move it to `src/game/components`?

[the remark this answers is not in the document]
Comment (itsalaidbacklife) [reply src/core/components/UsernameToolTip.vue:1]: Good question. The stories files are for storybook which is a separate tool that essentially instantiates components just to render them statically so you can see how they look. They don't count as real source code (since they're effectively a playground for instantiating components) and don't affect where we put components/how we think about which components belong where. So keep it in `src/game/components`

File: src/routes/home/components/GameListItem.vue [hunk 7]
```diff
@@ -55,7 +55,7 @@
 </template>
 
 <script>
-import GameStatus from '../../utils/GameStatus.json';
+import GameStatus  from '_/utils/GameStatus.json';
```
Comment (itsalaidbacklife) [inline src/routes/home/components/GameListItem.vue:58]: nitpick: extra whitespace
```suggestion
import GameStatus from '_/utils/GameStatus.json';
```

File: src/stores/gameList.js [hunk 8]
```diff
@@ -1,7 +1,7 @@
 import { defineStore } from 'pinia';
 import { cloneDeep } from 'lodash';
 import { io } from '@/plugins/sails.js';
-import GameStatus from '../../utils/GameStatus.json';
+import GameStatus  from '_/utils/GameStatus.json';
```
Comment (itsalaidbacklife) [inline src/stores/gameList.js:4]:
```suggestion
import GameStatus from '_/utils/GameStatus.json';
```

**Review by itsalaidbacklife — COMMENTED** [review]
@arnaut08 excellent work. This all looks right. I have two whitespace nitpicks in the comments. Other than that, the only thing to do is to fix the merge conflicts. Let me know if you'd like help navigating them. 

This is a great reorganization that I'm looking forward to finalizing. Thanks for your contribution!

**Comment by itsalaidbacklife** [comment]
@arnaut08 this is great. There are just two remaining merge conflicts due in 
```
src/components/HowItWorksDialog.vue
src/views/RulesView.vue
```
which were just updated today. Apologies that this has been a moving target. I can stop merging other PR's until this is done so that your update can go live before other things go in because you've been working on this for a while and it is so high-impact

**Review by itsalaidbacklife — APPROVED** [review]
Great work, thanks for taking this on!
