### PR TITLE
Fix/signup img

### LINKED ISSUE #460: [Bug]: Signup page background image doesn’t resolve
### Bug Summary

After #450, the background image in the signup page 404’s due to incorrect url

### Detailed Description

image

additionally the heading overflows on portrait mobile

### Current Behavior

image

### Expected Behavior

The image loads and the cuttle.cards heading fits within the screen on mobile

### Steps to Reproduce

1.
2.
3.

### PR DESCRIPTION
**Pull request by itsalaidbacklife**
Fixes a bug where the background image on the signup page doesn't load. I do not however, understand why this change fixes it...
## Issue number

Relevant issue number (e.g. #404): Resolves #460 

## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

### CODE REVIEW

File: src/views/LoginView.vue [hunk 1]
```diff
@@ -288,7 +288,9 @@ export default {
   min-height: 100vh;
   text-align: center;
   color: #FFF4D7;
-  background: center / cover no-repeat  url('img/game/board-background.svg');
+  background-image: url('/img/game/board-background.svg');
+  background-size: cover;
+  background-position: center;
```
Comment (itsalaidbacklife) [inline src/views/LoginView.vue:293]: I have no idea why this should make a difference @seriouslysean @Haviles04... But I deployed this to prod without merging and it works
image


I'm asking in the vue discord to see if anyone can explain why this difference matters

**Comment by itsalaidbacklife** [comment]
Result:
image

File: src/views/LoginView.vue (hunk 1 above)
Comment (itsalaidbacklife) [reply src/views/LoginView.vue]: Update: needed `url(/img...)` not just `url(img...)` prefix / indicates the domain root

File: src/views/LoginView.vue [hunk 2]
```diff
@@ -288,7 +288,7 @@ export default {
   min-height: 100vh;
   text-align: center;
   color: #FFF4D7;
-  background: center / cover no-repeat  url('img/game/board-background.svg');
+  background: center / cover no-repeat  url('/img/game/board-background.svg');
```
Comment (itsalaidbacklife) [inline src/views/LoginView.vue:291]: This was the essential fix. Need the prefix / to point to domain root

File: src/views/LoginView.vue [hunk 3]
```diff
@@ -357,24 +357,15 @@ export default {
...
-  width: 85%;
-  
-}
-}
-
-@media (orientation: landscape) and (max-width: 960px) {
-  #logo {
-    width: 64px;
-    height: 64px;
-    margin: -16px auto -32px;
```
Comment (itsalaidbacklife) [inline src/views/LoginView.vue:377]: This caused weirdness and looked wrong:
image

This way the logo is a little big on mobile landscape, but still within reason

Comment (itsalaidbacklife) [reply src/views/LoginView.vue:377]: Result:
image
