### PR TITLE
Fixed the sorting order

### LINKED ISSUE #110: Scrap should sort in scuttle order
### Bug Summary

The scrap pile should account for suit when sorting so that cards appear in the order of scuttle priority 

### Detailed Description

Currently when sorting the scrap by rank, suit is ignored, resulting in awkward discrepancies from the the expected order.

We should update the CardListSortable to sort by rank then suit (this will also entail updating the associated tests).

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps to Reproduce

_No response_

### PR DESCRIPTION
**Pull request by Bhoomiika**
Title: Fix Sorting Order Issue in Scrap Pile

Description:
This pull request addresses the sorting issue in the scrap pile, ensuring that cards appear in the correct order of scuttle priority. The problem was observed when sorting the scrap by rank, where the suit was ignored, leading to discrepancies from the expected order.

Problem:
Currently, the sorting logic only considers the rank of the cards, disregarding the suit. This resulted in cards being incorrectly ordered in the scrap pile, leading to an awkward display and inconsistent user experience.

Solution:
To resolve this, I have updated the CardListSortable component to sort the cards by both rank and suit. Now, the cards in the scrap pile will be sorted based on their rank, and in case of equal rank, they will be further sorted by suit. This ensures a proper scuttle order, enhancing the visual representation and usability of the scrap pile.

Changes Made:

Modified the sorting logic in the CardListSortable component to sort cards by both rank and suit.
Updated associated tests to reflect the new sorting order and ensure correctness.
Testing:
I have thoroughly tested this change by creating various scenarios with different card ranks and suits. I also used the provided tests to validate that the sorting order is now correct and consistent.

This fix enhances the overall user experience by presenting the scrap pile in the expected order, improving the game's interface and user interaction. I am confident that this solution addresses the reported issue effectively.

Please review and merge this pull request to incorporate the fix into the main branch. Thank you!

Fixes #110

### CODE REVIEW

**Comment by Bhoomiika** [comment]
Hey, this is my first time contributing to open source, I hope I have resolved the issue [Scrap should sort in scuttle order #110](https://github.com/cuttle-cards/cuttle/issues/110) Successfully, if there are any suggestions or improvements please let me know.
If this is correct pls approve the merge request.

File: src/components/GameView/CardListSortable.vue [hunk 1]
```diff
@@ -54,20 +54,10 @@ export default {
       type: String,
       default: 'No Cards Yet',
     },
-    /**
-     * Prefix used to identify where this card is in UI
-     * Used to generate data-* selectors for e2e testing
-     * @example 'scrap-dialog' for this prop
-     * results in labeling cards like
-     *     data-scrap-dialog-card="<suite>-<rank>"
-     */
```
Comment (itsalaidbacklife) [inline src/components/GameView/CardListSortable.vue:63]: Is there any particular reason why you opted to remove this comment? Given that the string is expected to be in a specific format, it seems useful to have an explanation of how it's constructed. I think it's better to leave the comment in, but I'm open to discussion about it

File: src/components/GameView/CardListSortable.vue [hunk 2]
```diff
@@ -84,19 +74,13 @@ export default {
...
     dataSelectorName() {
       return `data-${this.dataSelectorPrefix}-card`;
     },
   },
   methods: {
-    /**
-     * Format data selector for a specific card into object for v-bind
-     * @example result: {'data-scrap-dialog-card': '1-3'}
-     * ^^^ the ace of spades in the scrap dialog
-     **/
```
Comment (itsalaidbacklife) [inline src/components/GameView/CardListSortable.vue:99]: Same as above; I think the particular formatting requirements of these stings warrant a comment to explain how they look and should be used. Again, I think it's helpful to discuss these things because in theory comments like this are more for helping new contributors than veteran maintainers, so your input is useful! Why did you choose to remove it? Do you think the code is easier to understand without this comment?

File: src/components/GameView/CardListSortable.vue [hunk 3]
```diff
@@ -37,7 +37,7 @@
 
 <script>
 import GameCard from '@/components/GameView/GameCard.vue';
-import { sortBy } from 'lodash';
+import { orderBy } from 'lodash'; // Changed import
```
Comment (itsalaidbacklife) [inline src/components/GameView/CardListSortable.vue:40]: I think you are completely right to swap this import and use `orderBy` instead. Once the code is updated though, I don't think the comment on this line will be helpful, because no one will need to know that the import used to be something else. No big deal, I think we can just take it out
```suggestion
import { orderBy } from 'lodash';
```

As a suggestion for how to frame your thinking about communicating these things, I like to use code comments for notes that are helpful to someone reading the current state of the code, and then to use PR comments (you can add comments to lines of the PR just like this in your own PR) to explain the reasoning for my changes. So this could be a use case for leaving a PR comment to note that you're changing the function used to sort, since this is the one that allows for sorting on multiple values. 

PR comments are good for describing how and why code is being changed, whereas code comments are good for describing why the code is the way it is right now, irrespective of changes. Just food for thought

**Review by itsalaidbacklife — COMMENTED** [review]
Nice work. The change in logic perfectly addresses the issue as written and your explanation in the PR description is helpful for understanding the change. Thank you! I have 2 nitpicks and a chore to request before this is merged and deployed:
1. Can you please go into `package.json` and update the `version` field a patch version i.e. from 4.4.5 to 4.4.6? (This is helpful for confirming what code is live in production)
2. Two of the comments you removed strike me as helpful to leave in. I'm happy to discuss in the PR comments whether they really are helpful and if not to remove them here, but pending further discussion I'd prefer to leave the two ones I remarked on (the ones that explain the shape of data-cy selectors) in the code. 

Thanks for your contribution!

**Comment by itsalaidbacklife** [comment]
@Bhoomiika we just merged another update so would you please merge main into your branch and then bump the package.json version to 4.4.6?

File: src/components/GameView/CardListSortable.vue (hunk 2 above)
Comment (Bhoomiika) [reply src/components/GameView/CardListSortable.vue:99]: Hi @itsalaidbacklife Thank you for reviewing the code, I have went through all the requested changes and will make the changes and update it.
For the comments, as I told you this is my first contribution and I was very excited, I have deleted the comments in haste  but will take care from next time and add the necessary comments where ever required, I understand the importance of comments these were really helpful for me to go through the code.

File: src/components/GameView/CardListSortable.vue (hunk 1 above)
Comment (Bhoomiika) [reply src/components/GameView/CardListSortable.vue:63]: No , I removed it in a haste , really sorry I will add all the necessary comments again thanks for the guidance.

File: src/components/GameView/CardListSortable.vue (hunk 2 above)
Comment (itsalaidbacklife) [reply src/components/GameView/CardListSortable.vue:99]: Okay no problem at all. This is why we do code review. Just glad to have gotten on the same page about it

File: src/components/GameView/CardListSortable.vue (hunk 3 above)
Comment (Bhoomiika) [reply src/components/GameView/CardListSortable.vue]: Hi @itsalaidbacklife I have added all the necessary comments and changed the version in package.json as requested, thanks for giving me this opportunity , I hope the code is up-to-date and the issue "Fix Sorting Order Issue in Scrap Pile" #477, has been resolved successfully, if it is so please accept the merge request.

File: src/components/GameView/CardListSortable.vue [hunk 4]
```diff
@@ -37,7 +37,7 @@
 
 <script>
 import GameCard from '@/components/GameView/GameCard.vue';
-import { sortBy } from 'lodash';
+import { orderBy } from 'lodash';
```
Comment (itsalaidbacklife) [inline src/components/GameView/CardListSortable.vue:40]:
```suggestion
import { orderBy } from 'lodash';
```

Extra white space

File: src/components/GameView/CardListSortable.vue [hunk 5]
```diff
@@ -84,15 +87,14 @@ export default {
   },
   computed: {
     sortedCards() {
-      return this.sortByRank ? sortBy(this.cards, 'rank') : [...this.cards];
+      return this.sortByRank ? orderBy(this.cards, ['rank', 'suit']) : [...this.cards]; // Changed to use orderBy
```
Comment (itsalaidbacklife) [inline src/components/GameView/CardListSortable.vue:90]: We don't need the permanent comment that thus was changed
```suggestion
      return this.sortByRank ? orderBy(this.cards, ['rank', 'suit']) : [...this.cards];
```

**Review by itsalaidbacklife — APPROVED** [review]
Nice work! Thanks for your contribution. I'm making a couple minor adjustments of fixing a merge conflict, removing white space and removing an extraneous comment

**Comment by Bhoomiika** [comment]
Hey @itsalaidbacklife , could you please tell me when my contribution will be merged ?

**Comment by Bhoomiika** [comment]
Hey @itsalaidbacklife Thanks for guiding me through the process and merging the code.
