### PR TITLE
Bug #405 blank background

### LINKED ISSUE #405: [Bug]: Navigating to the url of a completed game gives you a blank background image
### Bug Summary

Navigating to a game url for a game that's over currently causes an uncaught error and leaves the user stuck on a dead page. We should detect this error and instead open a dialog that invites the user to navigate home.

### Detailed Description

Navigating to a completed game url like /#/game/1 currently causes an error that leaves the user on a blank page like this:
image

We should fix this so that users instead get a dialog that explains that this game is over and that they should go home, with a button to bring them to the home screen

### Current Behavior

The blank screen appears

### Expected Behavior

A dialog appears with:

Title: Oops!
Body: This game is over, nothing to see here
Actions: Button that says Go Home which behaves the same as the GameOverDialog's Go Home button

### Steps to Reproduce

1. Sign up and start a game with two players
2. End the game (by playing it out, conceding etc)
3. Wait for the GameOver dialog to appear and refresh the page
4. You'll see this screen
5. 
image

### PR DESCRIPTION
**Pull request by Haviles04**
## Issue number

Relevant issue number: Fixes #405 

## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [x] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change
 
- Added a Game unavailable overlay that matches waiting for game to start overlay
- Moved new overlay and reauthenticate dialog into a new Game-unavailable-view component.
- Wrote test for new overlay.

image

### CODE REVIEW

**Review by itsalaidbacklife — CHANGES_REQUESTED** [review]
Looking good. Requesting to pull the game unavailable overlay into its own component and for us to take a look at the computed prop that renders it

File: src/components/GameView/GameUnavailableView.vue [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+        <v-btn
+          color="secondary"
+          class="mt-4"
+          data-cy="leave-unavailable-game-button"
+          :loading="leavingGame"
+          @click="this.$router.push('/')"
+        >
+          Go Home
+        </v-btn>
+      </v-overlay>
```
[the remark this answers is not in the document]
Comment (seriouslysean) [reply src/components/GameView/GameUnavailableView.vue:30]: Split it for sure, separation of concerns imo.

File: src/components/GameView/GameUnavailableOverlay.vue [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+      Go Home
+    </v-btn>
+  </v-overlay>
+</template>
+
+<script>
+export default {
+  name: 'GameUnavailable',
+  props: {
+    unavailableGame: {
```
Comment (itsalaidbacklife) [inline src/components/GameView/GameUnavailableOverlay.vue:30]: Let's rename this `show`
```suggestion
    show: {
```

File: src/components/GameView/GameUnavailableOverlay.vue [hunk 3]
```diff
@@ -0,0 +1,56 @@
+<template>
+  <v-overlay
+    data-cy="unavailable-game-overlay"
+    id="unavailable-game-scrim"
+    v-model="unavailableGame"
```
Comment (itsalaidbacklife) [inline src/components/GameView/GameUnavailableOverlay.vue:5]: Instead of a 2-way v-model binding let's just use a one-way model-value binding:
```suggestion
    :model-value="show"
```

Comment (itsalaidbacklife) [reply src/components/GameView/GameUnavailableOverlay.vue:5]: v-model is for when you want to set the child's model value from the parent but also sync up the parent's variable with the child when the child emits an update, which we don't need to do here. This is more straightforward top-down prop assignment

File: src/views/GameView.vue [hunk 4]
```diff
@@ -1,9 +1,10 @@
 <template>
   <div id="game-view-wrapper">
-    <!-- Unauthenticated/Must re-log in -->
+    <!-- Unauthenticated/Must re-log in/ Unavailable game -->
     <template v-if="$store.state.game.myPNum === null">
```
Comment (itsalaidbacklife) [inline src/views/GameView.vue:4]: Do we still need this v-if? it looks like it'd be unnecessary with the logic in the `<game-unavailable-view>` itself

File: src/components/GameView/GameUnavailableOverlay.vue [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+  text-align: center;
+}
+.overlay-header {
+  font-weight: bold;
+  background-color: rgba(var(--v-theme-surface-2));
+  color: rgba(var(--v-theme-surface-1));
+  padding: 24px;
+  text-align: center;
+  width: 100vw;
+}
```
Comment (itsalaidbacklife) [inline src/components/GameView/GameUnavailableOverlay.vue:55]: Now that we're using these styles in another place, it'd be good to define a `BaseOverlay` component that can accommodate this and the component here as well as the styles in the existing `GameOverlays`. That can reasonably be scoped into a separate issue, though

File: package-lock.json [hunk 6]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "cuttle",
-  "version": "4.3.20",
+  "version": "4.3.22",
```
Comment (itsalaidbacklife) [inline package-lock.json:3]: Going forward, let's refrain from updating package-lock.json's version field manually. It updates to match `package.json` whenever we run `npm install`, which means that we can use the version here as a record of the last time that command was run. This is fine for now, but we can leave it off next time

File: package.json [hunk 7]
```diff
@@ -1,7 +1,7 @@
 {
   "name": "cuttle",
   "description": "The deepest card game under the sea",
-  "version": "4.3.21",
+  "version": "4.3.22",
```
Comment (itsalaidbacklife) [inline package.json:4]: Merge main into this and then bump to 4.3.25

File: src/components/GameView/GameUnavailableOverlay.vue (hunk 5 above)
Comment (itsalaidbacklife) [reply src/components/GameView/GameUnavailableOverlay.vue:55]: https://github.com/cuttle-cards/cuttle/issues/430

File: src/views/GameView.vue (hunk 4 above)
Comment (Haviles04) [reply src/views/GameView.vue:4]: without it, I get a blank game background.

File: src/components/GameView/GameUnavailableView.vue [hunk 8]
```diff
@@ -0,0 +1,35 @@
+<template>
+  <div>
+    <!-- Reauthenticate-->
+    <template v-if="mustReauthenticate">
+      <reauthenticate-dialog v-model="mustReauthenticate" />
+    </template>
+    <!-- Game doesn't exist-->
+    <template v-else>
+      <game-unavailable-overlay :unavailableGame="unavailableGame" />
+    </template>
```
[the remark this answers is not in the document]
Comment (Haviles04) [reply src/components/GameView/GameUnavailableView.vue]: I pulled up devtools after I switched them and it looks like there is no store,state,game.id until you're authenticated so the reauthenticate dialog no longer works

File: src/views/GameView.vue (hunk 4 above)
Comment (Haviles04) [reply src/views/GameView.vue:4]: So, I was able to get the game to load properly, but upon removing this v-if I'm getting a typeerror 
` kingCount(player) {
      return player.faceCards.reduce((kingCount, card) => kingCount + (card.rank === 13 ? 1 : 0), 0);
    }, `  TypeError: Cannot read properties of null (reading 'faceCards')

File: src/store/modules/game.js
Comment (Haviles04) [inline src/store/modules/game.js:1]: I added resetting the state on game end, the store wasn't resetting at the end of the game, so if you had just finished and then went to the url of any game number, the screen would display the last setup of the last game you played.

Comment (itsalaidbacklife) [reply src/store/modules/game.js:1]: Good catch

File: tests/e2e/specs/in-game/reconnecting.spec.js [hunk 9]
```diff
@@ -664,3 +662,34 @@ describe('Reconnecting to a game', () => {
...
+
+  it('Shows unavailable game dialog, then return home', () => {
+    cy.loadGameFixture(0, {
+      p0Hand: [Card.SEVEN_OF_CLUBS],
+      p0Points: [Card.SEVEN_OF_DIAMONDS, Card.SEVEN_OF_HEARTS],
+      p0FaceCards: [],
+      p1Hand: [],
+      p1Points: [],
+      p1FaceCards: [],
+    });
```
Comment (itsalaidbacklife) [inline tests/e2e/specs/in-game/reconnecting.spec.js:679]: Since the test doesn't care which cards are where we can skip loading a flame fixture 
```suggestion
```

**Review by itsalaidbacklife — APPROVED** [review]
Nice work. One last nit in the test

File: src/views/GameView.vue (hunk 4 above)
Comment (itsalaidbacklife) [reply src/views/GameView.vue:4]: I'm comfortable leaving it for now. We can revisit this if it proves valuable to do so

**Review by itsalaidbacklife — APPROVED** [review]
👍
