### PR TITLE
fix: replace Math.min() with Math.max() to prevent player count from …

### LINKED ISSUE #745: [Bug]: Player counts on games in the home view can be negative or greater than two
### Bug Summary

The HomeView shows games available to join. They should show 0/2, 1/2, or 2/2 players. Sometimes they can show -1/2 or 3/2

### Detailed Description

See pic:
Screen_Shot_2023-11-02_at_12 27 26_PM

This happens sometimes when socket messages are missed intermittently e.g. to players join a lobby and then leave it, but the your client misses the second player joined. So the event stream looks to your client like: join, leave, leave. This sets the player count to -1 instead of zero.

To fix this easily we can update the gameList store so that the `joinGame()` and `otherLeftGame()` actions which increment and decrement player counts use `Math.min()` and `Math.max()` respectively to ensure that the player count never goes above 2 or below 0. So instead of 
```
updatedGame.numPlayers++;
```

we’d have
```
updatedGame.numPlayers = Math.min(2, updatedGame.numPlayers + 1)
```

and the reciprocal for otherLeftGame 

### Current Behavior

The player counts of games in the gameList can sometimes be < 0 or > 2.

### Expected Behavior

The player counts are always either 0, 1, or 2

### Steps to Reproduce

1.
2.
3.

### PR DESCRIPTION
**Pull request by itsalaidbacklife**
…becoming negative

## Issue number

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #745 (again)

## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [ ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

### CODE REVIEW

File: src/stores/gameList.js [hunk 1]
```diff
@@ -59,7 +59,7 @@ export const useGameListStore = defineStore('gameList', {
     otherLeftGame(gameId) {
       const updatedGame = this.openGames.find((game) => game.id === gameId);
       if (updatedGame) {
-        updatedGame.numPlayers = Math.min(0, updatedGame.numPlayers - 1);
+        updatedGame.numPlayers = Math.max(0, updatedGame.numPlayers - 1);
```
Comment (seriouslysean) [inline src/stores/gameList.js:62]: Is this the best way to do that? What’s the range this can feasibly be? The typical game will be 0 with no one, 1 (lobby) or 2 (lobby/game) which would be:

- min: -1, 0, 1?
- max: 0, 1, 2?

Does it make more sense to count this a different way and just prevent it from going below 0?

Alternatively if you want to be extra safe pull it out to a utility and test it via vitest.

**Review by seriouslysean — APPROVED** [review]
Solution is fine but I have some questions.

File: src/stores/gameList.js (hunk 1 above)
Comment (itsalaidbacklife) [reply src/stores/gameList.js:62]: @seriouslysean yes this is a kludge or rather a fix to a previous kludge.
1. The player count is expected to be exactly 0, 1, or 2
2. I agree that it makes sense to store it a different way. Specifically instead of a number, we should store the users of the objects in the games so that we could later display their usernames if we wanted to, and so that the count is just the length of the server-provided array of players, which should reduce the chance for desync due to connection issues

I think it's overkill to pull this line into a utility b/c it's an intermediary solution anyway. I've written #755 to capture a better solution
