### PR TITLE
Bug #871 /Game and /Spectate bring you to blank screen

### LINKED ISSUE #871: [Bug]: /Game and /Spectate bring you to blank screen
### Bug Summary

Navigating to /game or /spectate without params brings you to a blank screen

### Detailed Description

Currently if you navigate to `/game` or `/spectate` without passing any `gameId` as a param you are navigate to a blank white page with the cuttle navbar above it. This should also be handled for `/lobby` and any other routes that might not have explicit paths

We should redirect these routes to the home view `/` 

### Current Behavior

Navigates to a blank white screen with navbar

### Expected Behavior

Navigates back to the home view

### PR DESCRIPTION
**Pull request by Haviles04**
## Issue number

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #871

## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change
Navigating to  `/game` or `/spectate` without a gameId will now show the game unavailable view
image

Navigating to the lobby without a gameId will give you a snackbar error 
image

### CODE REVIEW

File: src/router.js [hunk 1]
```diff
@@ -123,7 +121,7 @@ const routes = [
   },
   {
     name: ROUTE_NAME_SPECTATE,
-    path: '/spectate/:gameId',
+    path: '/spectate/:gameId?',
```
Comment (seriouslysean) [inline src/router.js:124]: You have some linting changes in here, looks like the only main change is the question mark for the conditional param.

**Review by seriouslysean — APPROVED** [review]
LGTM! Nice work 👍🏼

**Review by itsalaidbacklife — APPROVED** [review]
