### PR TITLE
Add class to fix card width for resolving seven

### LINKED ISSUE #179: Jacks and Deck Cards (during 7) are small in Firefox
### Bug Summary

We recently switched the card images to .svg’s which need an explicit size set. It is likely that the jacks and the deck cards during 7 resolution are missing that explicit size

### Detailed Description

Cared images of jacks and of the cards in the deck display very small or even I fail to display on Firefox 

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps to Reproduce

1. Open the app in Firefox 
2. Play a jack or a 7
3. See the cards fail to load or load too small

### PR DESCRIPTION
**Pull request by thomasjvu**
## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle#run-the-tests))
- [ ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

Adds class to fix card width when resolving seven. Fixes #179

### CODE REVIEW

**Comment by thomasjvu** [comment]
Seven resolution now looks good on Firefox with card images appearing at a normal size. Screenshot of result below.

image

File: client/js/views/GameView.vue [hunk 1]
```diff
@@ -1191,6 +1191,10 @@ export default {
   grid-area: decks;
 }
 
+.resolving-seven-size {
+    width: 9.5rem;
+}
```
Comment (itsalaidbacklife) [inline client/js/views/GameView.vue:1196]: This looks good--let's move it down inside the block for `.reveal-top-two {}` block and add a & in front of the selector like 
```suggestion
& .resolving-seven-card {
    width: 9.5rem;
}
```
The & is an alias for the nesting, so that means it'd apply to something with the `.resolving-seven-card` class that's inside the `.reveal-top-two` element.

While we are at it, let's rename the class to resolving-seven-card instead of -size so that we can use the same selector in case we need to apply other styles to these cards besides size

**Review by itsalaidbacklife — CHANGES_REQUESTED** [review]
Looks good. Let's change the class name and move the css 8 lines down into the block describing its parent

**Comment by thomasjvu** [comment]
Hi, I just pushed a new commit onto my fork's main branch that accounts for the changes of:

- renaming the class to .resolving-seven-card
- moving the css into the parent .reveal-top-two while also adding the & nesting alias

I double checked to make sure that everything still looks okay, which it does. Screenshot below. 

image

**Review by itsalaidbacklife — APPROVED** [review]
Looks great! Thanks for the fix
