### PR TITLE
Fix Issue 932

### LINKED ISSUE #932: [Bug]: RulePreviewDialog is too wide on small devices
### Bug Summary

The `RulePreviewDialog` is too wide on portrait mode phones

### Detailed Description

See pic:
image

We should shrink this down, either by setting a max-width that is a fraction of the viewport width, or using breakpoints for medium and down size devices <960px (because 960 is the next-largest breakpoint above where the issue happens).

### Current Behavior

The dialog stretches past the width of the screen on devices <660px wide.

### Expected Behavior

The dialog should be shrunk down to fit on these devices so that the x button (close) and the full image are visible.

### Steps to Reproduce

1. Open the RulesView on a device < 660px wide
2. Click on the "Play Video" button for one of the rule previews

### PR DESCRIPTION
**Pull request by Plubedam**
## 932
- Resolves #932

## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [ ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Additional info
Decided to use 90vw as max-width of dialog.

### CODE REVIEW

File: src/routes/rules/components/RulePreviewDialog.vue [hunk 1]
```diff
@@ -73,3 +73,10 @@ const preloadImage = () => {
   img.src = props.imageUrl;
 };
 </script>
+
+<style>
```
Comment (itsalaidbacklife) [inline src/routes/rules/components/RulePreviewDialog.vue:77]: All style blocks should be scoped to prevent bleeding across components 
```suggestion
<style scoped>
```

File: src/routes/rules/components/RulePreviewDialog.vue [hunk 2]
```diff
@@ -73,3 +73,10 @@ const preloadImage = () => {
...
+.game-overlay {
+  width: 650px;
+  max-width: 90vw;
+}
```
Comment (itsalaidbacklife) [inline src/routes/rules/components/RulePreviewDialog.vue:81]: Can you send a couple screenshots how this looks on a device that's say 600px vs 1920px wide?

**Review by itsalaidbacklife — COMMENTED** [review]
Nice work, this should improve this component. Please send screenshots per the comment & set the style block to scoped

File: src/routes/rules/components/RulePreviewDialog.vue (hunk 2 above)
Comment (Plubedam) [reply src/routes/rules/components/RulePreviewDialog.vue:81]: 600px wide:
Captura de pantalla 2024-06-07 193449
1920px wide:
Captura de pantalla 2024-06-07 193533

**Review by itsalaidbacklife — APPROVED** [review]
