### PR TITLE
Bug #697 Fix player hand sorting

### LINKED ISSUE #697: [Bug]: Player hand sorts after first move
### Bug Summary

Player hand sorts after first move instead of initially being sorted

### Detailed Description

Currently the players hand is not sorted until after the first move, this seems to be because `this.myPNum  === null` and therefore not firing the sort function

### Current Behavior

Hand sorts after 1st move

### Expected Behavior

Hand to be sorted from beginning

### Steps to Reproduce

1.
2.
3.

### PR DESCRIPTION
**Pull request by Haviles04**
## Issue number

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #697 

## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

- Removed unnecessary `resetState()` from socket call
- Set `myPNum` before `updateGame()` on `requestSubscribe()`
- Reordered and renamed `updateGameThanResetPNumIfNull()`

### CODE REVIEW

File: src/stores/game.js [hunk 1]
```diff
@@ -293,15 +293,15 @@ export const useGameStore = defineStore('game', {
...
+      this.resetPNumIfNull(game);
+      this.updateGame(game);    
     },
-    resetPNumIfNull() {
+    resetPNumIfNull(game) {
       const authStore = useAuthStore();
       // Set my pNum if it is null
       if (this.myPNum === null) {
-        let myPNum = this.players.findIndex((player) => player.username === authStore.username);
+        let myPNum = game.players.findIndex((player) => player.username === authStore.username);
```
Comment (Haviles04) [inline src/stores/game.js:304]:
```suggestion
        let myPNum = game.players.findIndex(({username}) => username === authStore.username);
```

File: src/plugins/sockets/inGameEvents.js [hunk 2]
```diff
@@ -30,8 +30,7 @@ export async function handleInGameEvents(evData) {
     }
     case SocketEvent.INITIALIZE: {
       // Update state
-      gameStore.resetState();
-      gameStore.updateGameThenResetPNumIfNull(evData.game);
+      gameStore.resetPNumIfNullThanUpdateGame(evData.game);
```
Comment (itsalaidbacklife) [inline src/plugins/sockets/inGameEvents.js:33]:
```suggestion
      gameStore.resetPNumIfNullThenUpdateGame(evData.game);
```

File: src/stores/game.js [hunk 3]
```diff
@@ -293,15 +293,15 @@ export const useGameStore = defineStore('game', {
       this.winnerPNum = winner;
       this.currentMatch = currentMatch;
     },
-    updateGameThenResetPNumIfNull(game) {
-      this.updateGame(game);
-      this.resetPNumIfNull();
+    resetPNumIfNullThanUpdateGame(game) {
+      this.resetPNumIfNull(game);
+      this.updateGame(game);
```
Comment (itsalaidbacklife) [inline src/stores/game.js:298]: Whitespace
```suggestion
      this.updateGame(game);
```

**Review by itsalaidbacklife — APPROVED** [review]
